require("freer.core")
require("freer.lazy")
-- require("freer.plugins-setup")
-- require("freer.plugins.comment")
-- require("freer.plugins.nvim-tree")
-- require("freer.plugins.lualine")
-- require("freer.plugins.telescope")
-- require("freer.plugins.nvim-cmp")
-- require("freer.plugins.lsp.mason")
-- require("freer.plugins.lsp.lspsaga")
-- require("freer.plugins.lsp.lspconfig")
-- require("freer.plugins.formatting")
-- require("freer.plugins.linting")
-- require("freer.plugins.indent-blankline")
